controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_tarea:
    path: /
    controller: App\Controller\TareaController::index

todosTareas:
    path: /api/tareas/{fecha_inicio}/{fecha_fin}/{estado}/{dias}
    controller: App\Controller\TareaController::todostareas
    methods: GET